### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by zabaat** [dpa99c/cordova-plugin-firebase#30]
**Describe the bug**
Trying to install, gets message:
**Failed to install 'cordova-plugin-cocoapod-supportx': Error: Unhandled "error" event. (The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.)**

**To Reproduce**
?

**Expected behavior**
The plugin to install

**Screenshots**

**Console Logs**
`PS C:\aCode\nomz\frontend\src-cordova> cordova plugin add cordova-plugin-firebasex
Installing "cordova-plugin-firebasex" for android
cordova-android version check failed ("C:\aCode\nomz\frontend\src-cordova\platforms\android\cordova\version"), continuing anyways.
Installing "cordova-plugin-cocoapod-supportx" for android
Unable to load PlatformApi from platform. Error: Cannot find module 'C:\aCode\nomz\frontend\src-cordova\platforms\android\cordova\Api.js'
Failed to install 'cordova-plugin-cocoapod-supportx': Error: Unhandled "error" event. (The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.)
    at EventEmitter.emit (events.js:186:19)
    at EventEmitter.module.exports.emit (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-common\src\events.js:71:17)
    at Object.getPlatformApiFunction (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\cordova\util.js:499:20)
    at Object.getPlatformApi (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:55:25)
    at handleInstall (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:593:29)
    at C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:816:13)
    at C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:570:49
Failed to install 'cordova-plugin-firebasex': Error: Unhandled "error" event. (The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.)
    at EventEmitter.emit (events.js:186:19)
    at EventEmitter.module.exports.emit (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-common\src\events.js:71:17)
    at Object.getPlatformApiFunction (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\cordova\util.js:499:20)
    at Object.getPlatformApi (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:55:25)
    at handleInstall (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:593:29)
    at C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:816:13)
    at C:\Users\brett\AppData\Roaming\nvm\v8.11.1\node_modules\cordova\node_modules\q\q.js:570:49
Unhandled "error" event. (The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.)`

**Plugin Version**
cordova-plugin-cocoapod-supportx 1.7.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-firebasex 3.0.6 "Google Firebase Plugin"

**Desktop (please complete the following information):**
 - OS: win 10
N/a

**Additional context**
cordova 8.1.2
android 8.0.0

**Comment by zabaat** [comment]
do the standard cordova platform remove, cordova platform add 
:slam:
